name: Cypress Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Install dependencies (cache speeds things up)
      - name: Install dependencies
        run: npm ci

      # Run Cypress tests (with built-in GitHub Action)
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome # can be chrome, firefox, or electron
